trigger: none

jobs:
  - job: MacOS
    strategy:
      matrix:
        catalina-std:
          image: macOS-10.15
          platform: x86-64
          version: 10.14
          buildType: "standard"
          prefix: "synergy"
        catalina-ent:
          image: macOS-10.15
          platform: x86-64
          version: 10.14
          buildType: "enterprise"
          prefix: "synergy-enterprise"
    pool:
      vmImage: $[ variables['image'] ]

    #As apparently the trigger set to none doesn't work
    condition: eq(variables['Build.Reason'], 'Manual')

    variables:
      QT_PATH: '/usr/local/opt/qt/bin'

    steps:
      - template: CI/checkout.yml
      - template: CI/MacOS/mac-build.yml